## CASO DE NEGOCIO:

Lo que se busca resolver o encontrar con este análisis son las tendencias de los videos de Youtube que
son publicados en Alemania

## OBJETIVOS DEL PROYECTO:

 - El objeto del proyecto es analizar el data set de videos que son tendencia en el país de Alemania donde nos encargaremos de organizar y limpiar
   los datos que sean necesarios para resolver el caso de negocio que planteamos.

   
## OBJETIVOS DE DATA SCIENCE

- La meta de nuestro análisis es visualizar de manera gráfica la cantidad de visitas que tiene los videos de cada estado de Alemania.

- Crear un modelo que pueda categorizar el número de visitas que tiene cada estado tomando en cuenta el número de vistas del video y del lugar
   donde se publicó, categorizar los videos que tiene más "me gustas" y las que tienen más "no me gustas", etc.

- Lograr que se cumplan todos los requerimientos planteados para este proyecto.

- Para este trabajo se eligió como variable dependiente el "número de visitas (views)", por ser una variable cuyo valor es el que llama
   más la atención de la gente que busca videos.

- Para este trabajo se eligió variables independientes como: latitud-longitud/Estado en el que se publicó, título del canal, tags/categoría id, likes/dislikes

 

## COMPRENSIÓN DE LOS DATOS

[Placeholder]

## DESCRIPCIÓN DEL DATASET:

El dataset que estamos usando para este trabajo contiene datos de los videos con más tendencia que provienen de Alemania, donde cuenta con
valores çomo el número de visitas del video, likes, dislikes, estado en el que se publicó,etc.

In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("DEvideos_cc50_202101.csv")

In [3]:
df['category_id']

0        24
1        23
2        24
3        27
4        24
         ..
40835    20
40836    24
40837    24
40838    20
40839    23
Name: category_id, Length: 40840, dtype: int64


## Recolectar los datos iniciales

In [ ]:
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,state,lat,lon,geometry
0,LgVi6y5QIjM,17.14.11,Sing zu Ende! | Gesangseinlagen vom Feinsten |...,inscope21,24,2017-11-13T17:08:49.000Z,"inscope21|""sing zu ende""|""gesangseinlagen""|""ge...",252786,35885,230,1539,https://i.ytimg.com/vi/LgVi6y5QIjM/default.jpg,False,False,False,Heute gibt es mal wieder ein neues Format... w...,Schleswig Holstein,54.783748,9.433315,POINT (9.433315388 54.78374778)
1,Bayt7uQith4,17.14.11,Kinder ferngesteuert im Kiosk! Erwachsene abzo...,LUKE! Die Woche und ich,23,2017-11-12T22:30:01.000Z,"Kinder|""ferngesteuert""|""Kinder ferngesteuert""|...",797196,53576,302,1278,https://i.ytimg.com/vi/Bayt7uQith4/default.jpg,False,False,False,Kinder ferngesteuert! Kinder lassen sich sooo ...,Nordrhein Westfalen,52.029988,8.530011,POINT (8.530011351000001 52.02998822)
2,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97190,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",Saarland,49.250390,6.970003,POINT (6.970003213 49.25039044)
3,AHtypnRk7JE,17.14.11,Das Fermi-Paradoxon,100SekundenPhysik,27,2017-11-12T15:00:01.000Z,"Physik|""Wissenschaft""|""Technik""|""Science-Ficti...",380247,31821,458,1955,https://i.ytimg.com/vi/AHtypnRk7JE/default.jpg,False,False,False,►Alle Videos: http://bit.ly/1fa7Tw3\n\n\n✚Snap...,Bayern,50.266607,10.966607,POINT (10.96660681 50.26660748)
4,ZJ9We4bjcg0,17.14.11,18 SONGS mit Kelly MissesVlog (Sing-off),rezo,24,2017-11-12T13:10:36.000Z,"kelly|""missesvlog""|""kelly song""|""bausa""|""bausa...",822213,100684,2467,10244,https://i.ytimg.com/vi/ZJ9We4bjcg0/default.jpg,False,False,False,18 Song Mashup über den (veränderten) Beat von...,Berlin,52.521819,13.401549,POINT (13.40154862 52.52181866)

## DESCRIPCIÓN DE LOS DATOS

"video_id": Conjunto de letras que cada video de Youtube tiene

"trending_date": Fecha en el que el video consiguió una mayor cantidad de visitas a comparación de otros días

"title": Nombre del video

"channel_title": Nombre del canal de la persona que publica los videos

"category_id": Categoría a la que pertenece el video(Ejemplo: 24,27,23...)

"publish_time": Fecha y hora en la que se publicó el video

"tags": 

"views": Número de ´visita que tiene el video

"likes":  Número de me gusta que tiene el video

"dislikes": Número de no me gusta que tiene el video

"comment_count": Número de comentarios que tiene el video

"thumbnail_link": Link de la imagen que contiene el video

"comments_disabled": Saber si se puede o no se puede comentar en el video(TRUE,FALSE)

"ratings_disabled": Saber si el contador de me gusta o no me gusta es visible(TRUE= No es visible, FALSE= Si es visible)

"videos_error_or_removed": Saber si el video puede ser visible para cualquier persona(TRUE= No se puede visualizar el video, FALSE= Si se puede visualizar el video)

"description": Descripción que contiene información sobre lo que trata el video

"state": Estado donde se publicó el video

"lat": Latitud geográfica donde se publicó el video

"lon": Longitud geográfica donde se publicó el video

"geometry": Registro de coordenadas de las geometrías donde se ubica el Estado dentro del planeta.


## Exploración de datos

In [5]:
pd.set_option('display.max_rows',100)

# Mostrar todas las columnas
pd.set_option('display.max_columns',10)


## CARGA DE DATOS

In [ ]:
df

,video_id,trending_date,title,channel_title,category_id,...,description,state,lat,lon,geometry
0,LgVi6y5QIjM,17.14.11,Sing zu Ende! | Gesangseinlagen vom Feinsten |...,inscope21,24,...,Heute gibt es mal wieder ein neues Format... w...,Schleswig Holstein,54.783748,9.433315,POINT (9.433315388 54.78374778)
1,Bayt7uQith4,17.14.11,Kinder ferngesteuert im Kiosk! Erwachsene abzo...,LUKE! Die Woche und ich,23,...,Kinder ferngesteuert! Kinder lassen sich sooo ...,Nordrhein Westfalen,52.029988,8.530011,POINT (8.530011351000001 52.02998822)
2,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,...,"One year after the presidential election, John...",Saarland,49.250390,6.970003,POINT (6.970003213 49.25039044)
3,AHtypnRk7JE,17.14.11,Das Fermi-Paradoxon,100SekundenPhysik,27,...,►Alle Videos: http://bit.ly/1fa7Tw3\n\n\n✚Snap...,Bayern,50.266607,10.966607,POINT (10.96660681 50.26660748)
4,ZJ9We4bjcg0,17.14.11,18 SONGS mit Kelly MissesVlog (Sing-off),rezo,24,...,18 Song Mashup über den (veränderten) Beat von...,Berlin,52.521819,13.401549,POINT (13.40154862 52.52181866)
...,...,...,...,...,...,...,...,...,...,...,...
40835,fn5WNxy-Wcw,18.14.06,KINGDOM HEARTS III – E3 2018 Pirates of the Ca...,Kingdom Hearts,20,...,Find out more about Kingdom Hearts 3: https://...,Hessen,51.300007,9.500030,POINT (9.500029661999999 51.30000694)
40836,zAFv43lxqHE,18.14.06,YMS: The Visit,YourMovieSucksDOTorg,24,...,Patreon: http://www.patreon.com/YMSTwitch: htt...,Berlin,52.521819,13.401549,POINT (13.40154862 52.52181866)
40837,zSXG5I6Y2fA,18.14.06,Ungut umgeschult – Grünwald als Ersthelfer am ...,Grünwald Freitagscomedy,24,...,Günter versucht sich als Ersthelfer bei einem ...,Saarland,49.250390,6.970003,POINT (6.970003213 49.25039044)
40838,5d115sePmaU,18.14.06,Assassin's Creed Odyssey: E3 2018 Welt-Enthüll...,Assassin's Creed DE,20,...,"Vom verstoßenen Söldner zum legendären Helden,...",Brandenburg,51.770418,14.329967,POINT (14.32996741 51.7704175)
40839,go-F6xvezAM,18.14.06,Гироскутер - Азбука Уральских Пельменей Б - Ур...,Уральские Пельмени,23,...,Популярный номер из нового шоу Азбука Уральски...,Hamburg,53.550025,9.999999,POINT (9.999999144 53.55002464)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40840 entries, 0 to 40839
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                40840 non-null  str
 1   trending_date           40840 non-null  str
 2   title                   40840 non-null  str
 3   channel_title           40840 non-null  str
 4   category_id             40840 non-null  int64
 5   publish_time            40840 non-null  str
 6   tags                    40840 non-null  str
 7   views                   40840 non-null  int64
 8   likes                   40840 non-null  int64
 9   dislikes                40840 non-null  int64
 10  comment_count           40840 non-null  int64
 11  thumbnail_link          40840 non-null  str
 12  comments_disabled       40840 non-null  bool
 13  ratings_disabled        40840 non-null  bool
 14  video_error_or_removed  40840 non-null  bool
 15  description             39288 non-null  str
 16  state                   40840 non-null  str
 17  lat                     40840 non-null  float64
 18  lon                     40840 non-null  float64
 19  geometry                40840 non-null  str
dtypes: bool(3), float64(2), int64(5), str(10)
memory usage: 5.4 MB

## INSPECCIÓN DE DATOS

"video_id": string

"trending_date": string 

"title": string

"channel_title": string 

"category_id": integer

"publish_time": string

"tags": string

"views": integer

"likes":  integer

"dislikes":integer

"comment_count": integer

"thumbnail_link": string

"comments_disabled": boolean

"ratings_disabled": boolean

"videos_error_or_removed": boolean

"description": string

"state": string

"lat": float

"lon": float

"geometry": string


## VERIFICAR LA CALIDAD DE DATOS

Debemos encontrar filas que tienen valores nulos

In [ ]:
filas_son_nulas = df[df.isnull().any(axis=1)]  # Con esto accedemos a las filas que tengan algún valor nulo en algunas de sus columnas

filas_son_nulas

,video_id,trending_date,title,channel_title,category_id,...,description,state,lat,lon,geometry
67,XEY-mcrPAjI,17.14.11,Hayattta Her Şey Var 13 Kasım 2017,Hayatta Her Şey Var,22,...,NaN,Saarland,49.250390,6.970003,POINT (6.970003213 49.25039044)
145,OA0vhAKUD0g,17.14.11,Outlander S03E09 i'm melting with you'',Ella bell,1,...,NaN,Bayern,50.266607,10.966607,POINT (10.96660681 50.26660748)
171,giUivdCbg0g,17.14.11,شاهد بالفيديو الهزة الارضية في داخل استديو قنا...,عراق فاملي-iraq family,22,...,NaN,Berlin,52.521819,13.401549,POINT (13.40154862 52.52181866)
175,AT76sOaT8Zk,17.14.11,คุยเเซ่บShow : เปิดใจ ลูก เมีย โจ บอยสเก๊าท์ ค...,Orange Mama,22,...,NaN,Schleswig Holstein,54.783748,9.433315,POINT (9.433315388 54.78374778)
254,R2ftFltzomA,17.15.11,Kim wird von Jacky psychisch zerstört! | Berli...,BerlinTagUndNacht,22,...,NaN,Hamburg,53.550025,9.999999,POINT (9.999999144 53.55002464)
...,...,...,...,...,...,...,...,...,...,...,...
40718,ZX1OmtsOEm4,18.14.06,Talat Bulut hakkında korkunç iddialar!,Söylemezsem Olmaz,22,...,NaN,Sachsen Anhalt,52.130421,11.620004,POINT (11.62000362 52.13042137)
40745,r5sOlv58s_k,18.14.06,180613 JIMIN & JUNGKOOK - 'Black Or White' Mic...,Jung Hyun Ran,22,...,NaN,Schleswig Holstein,54.783748,9.433315,POINT (9.433315388 54.78374778)
40753,b9-AsfPeohg,18.14.06,Erdoğan'ın gizli 24 Haziran konuşması sızdırıl...,by x,25,...,NaN,Brandenburg,51.770418,14.329967,POINT (14.32996741 51.7704175)
40811,OqjwJ3EY1V4,18.14.06,TOKOMI WAPI 13 06 2018 BA BUKI NDAKU YA BA ROSSY,NDEKO ELIEZER TOKOKOMA,25,...,NaN,Bayern,50.266607,10.966607,POINT (10.96660681 50.26660748)
40812,-FO9-XfQyMU,18.14.06,Power of Love Το τέλος της 83ης μέρας 13/6/18,OUTERLIMITS-LYKOS TEAM HELLAS,24,...,NaN,Schleswig Holstein,54.783748,9.433315,POINT (9.433315388 54.78374778)

Luego, hay que encontrar la cantidad total de filas con valores nulos

In [ ]:
print(df.isnull().sum().sum()) # Total de valores nulos

1552

Encontrar la cantidad total de filas con valores nulos

In [ ]:
print(df.isnull().sum()) # Total de valores nulos por columna

video_id                     0
trending_date                0
title                        0
channel_title                0
category_id                  0
publish_time                 0
tags                         0
views                        0
likes                        0
dislikes                     0
comment_count                0
thumbnail_link               0
comments_disabled            0
ratings_disabled             0
video_error_or_removed       0
description               1552
state                        0
lat                          0
lon                          0
geometry                     0
dtype: int64

Con esto podemos darnos cuenta de que la mayoría de valores nulos se encuentra en la columna "description"


## PREPARACIÓN DE LOS DATOS

Tomando en cuenta que un video puede NO tener una descripción, cambiaremos sus valores nulos a un valor "sin descripcion"

In [ ]:
df['description'] = df['description'].fillna("Sin descripcion")

print(df.isnull().sum())

video_id                  0
trending_date             0
title                     0
channel_title             0
category_id               0
publish_time              0
tags                      0
views                     0
likes                     0
dislikes                  0
comment_count             0
thumbnail_link            0
comments_disabled         0
ratings_disabled          0
video_error_or_removed    0
description               0
state                     0
lat                       0
lon                       0
geometry                  0
dtype: int64